### ISSUE TITLE
Give us KittenBot 3

### ISSUE THREAD

**Issue by Resurrection3387** [Sqaaakoi/KittenBot#1]
Give us KittenBot 3

**Comment by Sqaaakoi** [comment]
Soon™

**Comment by Sqaaakoi** [comment]
I'm a lazy developer.

**Comment by Resurrection3387** [comment]
Pretty obvious lmao

**Comment by Sqaaakoi** [comment]
> Pretty obvious lmao

Yeah, but I'm gonna work on it tonight (for real)

**Comment by Resurrection3387** [comment]
> null
Okay

**Comment by Resurrection3387** [comment]
>Yeah, but I'm gonna work on it tonight (for real) hahayes
I want cringy emojis

**Comment by Resurrection3387** [comment]
>Yeah, but I'm gonna work on it tonight (for real) hahayes

Are sure?

**Comment by Resurrection3387** [comment]
You literally tweeted it isn't the focus

**Comment by Sqaaakoi** [comment]
"yes"

**Comment by Sqaaakoi** [comment]
I'm being productive!

**Comment by Sqaaakoi** [comment]
Core is almost finished.

**Comment by Sqaaakoi** [comment]
Core is done and is about to be published
